### ISSUE TITLE
help me please, in path '/formManagement/'

### ISSUE THREAD

**Issue by miko1852** [GinoLlerena/dynamicform#2]
index.js:1437 Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (at FormElement.js:82)
    in div (at FormElement.js:80)
    in TextElement (at FormElementComponent.js:40)
    in FormElementComponent (at FormManagement.js:40)
    in ListElements (at FormManagement.js:71)
    in form (at FormManagement.js:69)
    in div (at FormManagement.js:68)
    in FormManagement (created by Context.Consumer)
    in Route (at App.js:37)
    in div (at App.js:17)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:16)
    in App (at src/index.js:6)

**Comment by GinoLlerena** [comment]
Now is fixed.
